export const FACEBOOK_GROUPS = {
  a: [
    { name: 'Laptop Buy & Sell Rwp/ ISLAMABAD', url: 'https://www.facebook.com/groups/287510136786026/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Laptop Buy & Sell Pakistan', url: 'https://www.facebook.com/groups/348315886290901/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Laptops Buy and Sell Rawalpindi Islamabad', url: 'https://www.facebook.com/groups/1654287465006163/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Laptops In Lahore Pakistan', url: 'https://www.facebook.com/groups/1436655256976867/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Used Laptops for Sale in UAE (Dubai)', url: 'https://www.facebook.com/groups/293529031175851/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'Used Laptop in UAE(Buy and Sell)', url: 'https://www.facebook.com/groups/1399479608354068/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'USED LAPTOPS UAE', url: 'https://www.facebook.com/groups/1390715798388627/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'laptop uae bur dubai', url: 'https://www.facebook.com/groups/1207468486769766/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'Buy & sell laptops 💻 in UAE', url: 'https://www.facebook.com/groups/286049852825433/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'The Laptops Market of UAE || 543650677 ||', url: 'https://www.facebook.com/groups/228937222845218/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'Used Laptops & Computers UAE', url: 'https://www.facebook.com/groups/3631954030226236/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'Used Laptop in UAE,Used Mobile Phone in Dubai,Used laptops abu Dhabi', url: 'https://www.facebook.com/groups/455542861526951/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'DUBAI LAPTOP BUY SELL', url: 'https://www.facebook.com/groups/2826101831007083/', country: 'UAE', niche: 'Buy/Sell' },
  ],
  b: [
    { name: 'Imported LoT Used Laptops Shop | Buy & Sell | BITS Computer', url: 'https://www.facebook.com/groups/430437444745066/', country: 'Global', niche: 'Buy/Sell' },
    { name: 'Soko Laptops', url: 'https://www.facebook.com/groups/www.rikeltech.co.ke/', country: 'Kenya', niche: 'Buy/Sell' },
    { name: 'Used Laptop shop in Lahore Pakistan', url: 'https://www.facebook.com/groups/870335647628755/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Laptop Market Kenya', url: 'https://www.facebook.com/groups/2503607303198022/', country: 'Kenya', niche: 'Buy/Sell' },
    { name: 'BUY & SELL ONLY LAPTOPS IN PAKISTAN', url: 'https://www.facebook.com/groups/1376506892648586/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'LAPTOP WALA LAHORE SALE AND PURCHASE OF LAPTOPS IN PAKISTAN', url: 'https://www.facebook.com/groups/665251902631773/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Laptops For Sale In Pakistan', url: 'https://www.facebook.com/groups/Laptops.for.sale.in.Pakistan/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Used Laptop For Sale In Lahore', url: 'https://www.facebook.com/groups/2321616504705557/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Pakistan Laptops Buy & Sell - New & Used in Lahore |Islamabad |Rawalpindi', url: 'https://www.facebook.com/groups/982432670207106/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Nairobi Laptops Market Place', url: 'https://www.facebook.com/groups/251282749838823/', country: 'Kenya', niche: 'Buy/Sell' },
  ],
  c: [
    { name: 'Computer Gaming Buy and Sell UAE-Abu Dhabi', url: 'https://www.facebook.com/groups/234152655336355/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'Ex uk laptops and electronics', url: 'https://www.facebook.com/groups/4775723345821477/', country: 'UK/UAE', niche: 'Electronics' },
    { name: 'used laptops and desktops computer dealers', url: 'https://www.facebook.com/groups/1636321320005793/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'Computer Desktop & Laptop Buy And sell', url: 'https://www.facebook.com/groups/3gacomputertrading/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'Dell laptops in UAE Dubai', url: 'https://www.facebook.com/groups/1464149717489134/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'Apple Store Pakistan', url: 'https://www.facebook.com/groups/468018704180772/', country: 'Pakistan', niche: 'Apple' },
    { name: 'Souq Laptop UAE', url: 'https://www.facebook.com/groups/350127229667902/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'PPG PAKISTAN PC GAMERS BUY & SELL', url: 'https://www.facebook.com/groups/pakpcgame/', country: 'Pakistan', niche: 'Gaming' },
    { name: 'Laptop Murang Bentahan', url: 'https://www.facebook.com/groups/195276603192380/', country: 'Philippines', niche: 'Buy/Sell' },
    { name: 'PC Buy and Sell', url: 'https://www.facebook.com/groups/pctyoubleshoot/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'PC Parts For Sale or free Discussion', url: 'https://www.facebook.com/groups/160493414156767/', country: 'Mixed', niche: 'Parts' },
    { name: 'PPG - Pakistani PC Gamers', url: 'https://www.facebook.com/groups/pakistanipcgamerss/', country: 'Pakistan', niche: 'Gaming' },
    { name: 'second hand phones', url: 'https://www.facebook.com/groups/980549026938673/', country: 'Mixed', niche: 'Phones' },
    { name: 'Gaming PC parts for sale buy and trade', url: 'https://www.facebook.com/groups/748686418089436/', country: 'Mixed', niche: 'Gaming parts' },
    { name: 'Laptop\'s below 15k', url: 'https://www.facebook.com/groups/589695865710768/', country: 'Mixed', niche: 'Budget' },
    { name: 'Computer Shop (SL)', url: 'https://www.facebook.com/groups/168553947827748/', country: 'Sri Lanka', niche: 'Computer shop' },
    { name: 'Laptop Buy & Sale', url: 'https://www.facebook.com/groups/323738708390859/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'Computer Technician Group', url: 'https://www.facebook.com/groups/343036160383203/', country: 'Mixed', niche: 'Technical' },
    { name: 'BULACAN laptop pc (buy and sell)', url: 'https://www.facebook.com/groups/396672837332532/', country: 'Philippines', niche: 'Buy/Sell' },
    { name: 'Refurbished laptop and Desktop - Pune', url: 'https://www.facebook.com/groups/494606867399611/', country: 'India', niche: 'Refurbished' },
    { name: 'Lanka second hand computer laptop hardware & accessories buy sell & repair', url: 'https://www.facebook.com/groups/501789713860743/', country: 'Sri Lanka', niche: 'Buy/Sell/Repair' },
    { name: 'Laptop Buy and Sale Srilanka 🇱🇰', url: 'https://www.facebook.com/groups/634191852080814/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: 'Laptop Market Sri Lanka | ලැප් ටොප් මාකට් ශ්‍රී ලංකා', url: 'https://www.facebook.com/groups/642333480402364/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: 'Laptops and Smartphones Kenya', url: 'https://www.facebook.com/groups/702139453890911/', country: 'Kenya', niche: 'Buy/Sell' },
    { name: 'NAIROBI LAPTOPS UNDER 10K MWEDTECH', url: 'https://www.facebook.com/groups/706926810029335/', country: 'Kenya', niche: 'Budget' },
    { name: 'Computer Accessories Buying & Selling 🇱🇰', url: 'https://www.facebook.com/groups/749668835087528/', country: 'Sri Lanka', niche: 'Accessories' },
    { name: 'Kenya Computer Market', url: 'https://www.facebook.com/groups/799829710833743/', country: 'Kenya', niche: 'Computer market' },
    { name: 'LAPTOP BATTERY & CHARGER RETAILER', url: 'https://www.facebook.com/groups/1056616971480168/', country: 'Mixed', niche: 'Accessories' },
    { name: 'SMARTPHONES AND LAPTOPS FOR SALE', url: 'https://www.facebook.com/groups/1502960433094410/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'Nigeria\'s Cheapest Laptops Sales Organisation', url: 'https://www.facebook.com/groups/cheapest2011/', country: 'Nigeria', niche: 'Buy/Sell' },
    { name: 'Buy or Sell Apple MacBook Pro iMac iPhone iPad Mac Mini iPod & More', url: 'https://www.facebook.com/groups/sellmac/', country: 'Mixed', niche: 'Apple' },
    { name: 'Used Laptops for sale in Dubai', url: 'https://www.facebook.com/groups/623329363211082/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'Used Laptop & Computer Coimbatore 9698887487', url: 'https://www.facebook.com/groups/1761568467600406/', country: 'India', niche: 'Buy/Sell' },
    { name: 'Laptop Lcd Screen and other accessories', url: 'https://www.facebook.com/groups/358777789879107/', country: 'Mixed', niche: 'Accessories' },
    { name: 'NAIROBI SOFT COMPUTER\'S AND LAPTOPS', url: 'https://www.facebook.com/groups/892350949608189/', country: 'Kenya', niche: 'Buy/Sell' },
    { name: 'Used Laptops Offer Sale - Imported From USA', url: 'https://www.facebook.com/groups/413673189590534/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'THE BEST GAMING LAPTOPS FOR SALE', url: 'https://www.facebook.com/groups/242121010932513/', country: 'Mixed', niche: 'Gaming' },
    { name: '(Laptop sale price.6000 7000 8000', url: 'https://www.facebook.com/groups/2323616751345847/', country: 'Mixed', niche: 'Budget' },
    { name: 'لابتوبات مستعملة وجديدة للبيع في الأردن', url: 'https://www.facebook.com/groups/685575520131383/', country: 'Jordan', niche: 'Buy/Sell' },
    { name: 'Laptop Buy and sell', url: 'https://www.facebook.com/groups/658716174764830/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'Malaysian PC/Laptop & Gaming Community', url: 'https://www.facebook.com/groups/514773388677142/', country: 'Malaysia', niche: 'Gaming' },
    { name: 'Laptops group', url: 'https://www.facebook.com/groups/1305980536463390/', country: 'Mixed', niche: 'Generic' },
    { name: 'Laptop Secrets & Buyer\'s Guide', url: 'https://www.facebook.com/groups/429349596180719/', country: 'Mixed', niche: 'Advice' },
    { name: 'ලැප්ටොප් අලුත්වැඩියාව සහ අලෙවිය Laptop repair & sales', url: 'https://www.facebook.com/groups/1782085025652651/', country: 'Sri Lanka', niche: 'Repair/Sales' },
    { name: 'Laptop Markert In Sri Lanka', url: 'https://www.facebook.com/groups/250648829403182/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: 'ලංකා ලැප්ටොප් වෙළෙඳපොළ | Lanka Laptop Market', url: 'https://www.facebook.com/groups/343660523882883/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: 'Refurbished laptop and Desktop - Hyderabad (India)', url: 'https://www.facebook.com/groups/1673965892648243/', country: 'India', niche: 'Refurbished' },
    { name: 'LaPtOp SeCoNdHaNd TeRpAkAi MaLaYsIa', url: 'https://www.facebook.com/groups/270531323542906/', country: 'Malaysia', niche: 'Buy/Sell' },
    { name: 'Jual Beli Laptop dan Accessories Malaysia', url: 'https://www.facebook.com/groups/440674726024406/', country: 'Malaysia', niche: 'Buy/Sell' },
    { name: 'Laptop Second And Sparepart Malaysia', url: 'https://www.facebook.com/groups/469755396479966/', country: 'Malaysia', niche: 'Buy/Sell/Parts' },
    { name: 'Komputer Terpakai Malaysia', url: 'https://www.facebook.com/groups/1816415991924761/', country: 'Malaysia', niche: 'Buy/Sell' },
    { name: 'Jual Beli Laptop Handphone KL Selangor', url: 'https://www.facebook.com/groups/1283211668534150/', country: 'Malaysia', niche: 'Buy/Sell' },
    { name: 'Laptop Buy and Sell Malaysia', url: 'https://www.facebook.com/groups/3459841277677033/', country: 'Malaysia', niche: 'Buy/Sell' },
    { name: 'Sale Swap your Games (UAE Elite Gamers)', url: 'https://www.facebook.com/groups/313720242979363/', country: 'UAE', niche: 'Gaming' },
    { name: 'Computers Laptops & Parts (පරිගණක හා අමතර උපාංග විකිණීම හා මිලදී ගැනීම )', url: 'https://www.facebook.com/groups/709769453853964/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: 'SL Laptops and Parts sale', url: 'https://www.facebook.com/groups/624733748560713/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: 'Laptop for Sale', url: 'https://www.facebook.com/groups/LaptopSaleLK/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: 'Laptop mobile phone buy and sell SL', url: 'https://www.facebook.com/groups/647771522820694/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: 'Laptop Buy & Sell - Sri Lanka', url: 'https://www.facebook.com/groups/776478297051590/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: 'PC Hut 💻👨‍💻👩‍💻laptops buy & sale', url: 'https://www.facebook.com/groups/1479647955542509/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: 'laptop sale srilanka', url: 'https://www.facebook.com/groups/320159256945210/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: '2nd Hand Laptops Sri Lanka', url: 'https://www.facebook.com/groups/764917618654924/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: 'Laptops Desktops Computers & Accessories in Sri Lanka Buy and Sell', url: 'https://www.facebook.com/groups/computersLanka/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: 'Sri lanka used laptops', url: 'https://www.facebook.com/groups/903471897077475/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: '🖥️ Pc | Laptop | 📲 Tech Items Sale in Sri Lanka 🇱🇰 💻', url: 'https://www.facebook.com/groups/5697637236976278/', country: 'Sri Lanka', niche: 'Buy/Sell' },
    { name: 'Buy And Sell Graphic Cards', url: 'https://www.facebook.com/groups/asianminers/', country: 'Mixed', niche: 'Parts' },
    { name: 'laptops Under 23500 kes', url: 'https://www.facebook.com/groups/315100992628165/', country: 'Kenya', niche: 'Budget' },
    { name: 'Cheap Laptops in Harare', url: 'https://www.facebook.com/groups/760366805691781/', country: 'Zimbabwe', niche: 'Budget' },
    { name: 'Computers on Sale', url: 'https://www.facebook.com/groups/1534126123539683/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'Used Tablets and Laptops in UAE', url: 'https://www.facebook.com/groups/2939381519678788/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'Laptop Community - Buy & Sell', url: 'https://www.facebook.com/groups/136166324588501/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'LapTop', url: 'https://www.facebook.com/groups/458584325571430/', country: 'Mixed', niche: 'Generic' },
    { name: 'HP ZBook Laptop users - مستخدمى لابتوب hp zbook', url: 'https://www.facebook.com/groups/hpzbook/', country: 'Mixed', niche: 'Business' },
    { name: 'laptop sale 2nd hand only!!!', url: 'https://www.facebook.com/groups/625204218610813/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'Fast Laptops & Computer sells', url: 'https://www.facebook.com/groups/514599671562043/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'Gaming Laptop Buy & Sell Group in Myanmar', url: 'https://www.facebook.com/groups/472787804384254/', country: 'Myanmar', niche: 'Gaming' },
    { name: 'Budget Laptops in Sri Lanka අඩුවට ලැප්ටොප් ලංකාවේ.', url: 'https://www.facebook.com/groups/965780795234065/', country: 'Sri Lanka', niche: 'Budget' },
    { name: 'لابتوبات السودان (Sudan\'s Laptops)', url: 'https://www.facebook.com/groups/676136580588371/', country: 'Sudan', niche: 'Buy/Sell' },
    { name: 'Second Hand Laptop', url: 'https://www.facebook.com/groups/1266192507435755/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'Cheap Ex UK Laptops in Kenya', url: 'https://www.facebook.com/groups/1936350136532601/', country: 'Kenya', niche: 'Buy/Sell' },
    { name: 'Cheap Laptops Philippines', url: 'https://www.facebook.com/groups/1796709040576151/', country: 'Philippines', niche: 'Buy/Sell' },
    { name: 'Pakistan Lahore Laptops Group', url: 'https://www.facebook.com/groups/598569442979698/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Laptops in Pakistan', url: 'https://www.facebook.com/groups/106372961487/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Laptops For Sale South Africa', url: 'https://www.facebook.com/groups/998715980242796/', country: 'South Africa', niche: 'Buy/Sell' },
    { name: 'Laptops under 20k in Kenya', url: 'https://www.facebook.com/groups/614206602104780/', country: 'Kenya', niche: 'Budget' },
    { name: 'used laptop computers uae', url: 'https://www.facebook.com/groups/244528283564844/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'USED LAPTOPS FROM SHARJAH', url: 'https://www.facebook.com/groups/1335475017462913/', country: 'UAE', niche: 'Buy/Sell' },
    { name: 'i&i Laptops Dubai plaza rwp', url: 'https://www.facebook.com/groups/273446038140191/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Refurbished Laptop Dealer', url: 'https://www.facebook.com/groups/478336959753179/', country: 'Mixed', niche: 'Refurbished' },
    { name: 'Used Computer & laptops', url: 'https://www.facebook.com/groups/411521959225674/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'buying and selling of old laptops', url: 'https://www.facebook.com/groups/2132583013739015/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'eTHIOPIA Electronics Sell and Buy | ONLY ORIGINAL PRODUCTS | DISCOUNT Price', url: 'https://www.facebook.com/groups/1020675471994284/', country: 'Ethiopia', niche: 'Buy/Sell' },
    { name: 'Hope Ethiopia Laptop &computer trading plc', url: 'https://www.facebook.com/groups/281253410605808/', country: 'Ethiopia', niche: 'Buy/Sell' },
    { name: 'Laptops & Cellphones Buy Sell Swap Harare Zimbabwe �', url: 'https://www.facebook.com/groups/162570545788800/', country: 'Zimbabwe', niche: 'Buy/Sell' },
    { name: 'لاب توب في الأردن Laptops in Jordan', url: 'https://www.facebook.com/groups/LaptopsinJordan/', country: 'Jordan', niche: 'Buy/Sell' },
    { name: 'لاب توب مصر - Laptop Egypt', url: 'https://www.facebook.com/groups/capitalgardens1/', country: 'Egypt', niche: 'Buy/Sell' },
    { name: 'Gaming Laptop Pinas 🇵🇭 (Official)', url: 'https://www.facebook.com/groups/243352200139984/', country: 'Philippines', niche: 'Gaming' },
    { name: 'Sell and buy laptop/Pc on Facebook in Mauritius', url: 'https://www.facebook.com/groups/laptopandpc/', country: 'Mauritius', niche: 'Buy/Sell' },
    { name: 'Computer And Laptop Buy & Sale in Faisalabad', url: 'https://www.facebook.com/groups/computer.and.laptop.buy.sale.in.faisalabad/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Laptop Buy And Sell Quality Laptop and Computer', url: 'https://www.facebook.com/groups/1002348395141134/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'laptop for sale in karachi', url: 'https://www.facebook.com/groups/843519456983897/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Egypt Laptops Community 🇪🇬', url: 'https://www.facebook.com/groups/egypt.laptop.community/', country: 'Egypt', niche: 'Buy/Sell' },
    { name: 'Computer Shop & Laptop prices in kenya', url: 'https://www.facebook.com/groups/2082086475394138/', country: 'Kenya', niche: 'Buy/Sell' },
    { name: 'Chennai used laptops', url: 'https://www.facebook.com/groups/404824450999835/', country: 'India', niche: 'Buy/Sell' },
    { name: 'LAPTOP\'S / COMPUTER DEALER', url: 'https://www.facebook.com/groups/3197438383895770/', country: 'Mixed', niche: 'Dealer' },
    { name: 'Laptop in Nigeria - Buy and Sell', url: 'https://www.facebook.com/groups/534712403664022/', country: 'Nigeria', niche: 'Buy/Sell' },
    { name: 'Laptops & Computers world', url: 'https://www.facebook.com/groups/605191911085712/', country: 'Mixed', niche: 'Generic' },
    { name: 'Laptop\'s market', url: 'https://www.facebook.com/groups/729062094706669/', country: 'Mixed', niche: 'Generic' },
    { name: 'Electronics in Ethiopia', url: 'https://www.facebook.com/groups/1603991223281545/', country: 'Ethiopia', niche: 'Electronics' },
    { name: 'Laptops & Computer Deals East Africa', url: 'https://www.facebook.com/groups/570701908309457/', country: 'East Africa', niche: 'Buy/Sell' },
    { name: 'Laptops Under 15k And Affordable Laptop Repairs Services Kenya.', url: 'https://www.facebook.com/groups/233571633786415/', country: 'Kenya', niche: 'Buy/Sell/Repair' },
    { name: 'Laptops for Sale in Kenya', url: 'https://www.facebook.com/groups/126508794446729/', country: 'Kenya', niche: 'Buy/Sell' },
    { name: 'Karachi Market Place Computers, Laptops & Accessories (Buy & Sell)', url: 'https://www.facebook.com/groups/3614008218844387/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'All Brand Laptop In USA Group', url: 'https://www.facebook.com/groups/allbrandlaptopinusa/', country: 'USA', niche: 'Buy/Sell' },
    { name: 'computer and laptop buy and sell in Karachi', url: 'https://www.facebook.com/groups/968680090359223/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Laptops below 20k', url: 'https://www.facebook.com/groups/1813434112806187/', country: 'Mixed', niche: 'Budget' },
    { name: 'LAPTOPS / COMPUTERS & PARTS - BUY, SELL & SWAP', url: 'https://www.facebook.com/groups/230021693860871/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'used laptops and desktops computer dealers', url: 'https://www.facebook.com/groups/1028633687245638/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'NAIROBI AFFORDABLE LAPTOPS', url: 'https://www.facebook.com/groups/141540252385159/', country: 'Kenya', niche: 'Budget' },
    { name: 'Used Computers , Desktops & Laptops', url: 'https://www.facebook.com/groups/usedlaptopsdelhi/', country: 'India', niche: 'Buy/Sell' },
    { name: 'Ethio Laptops Sell and Buy', url: 'https://www.facebook.com/groups/128555713638085/', country: 'Ethiopia', niche: 'Buy/Sell' },
    { name: 'Murang Laptop Buy And Sell Pinas', url: 'https://www.facebook.com/groups/1641101999437298/', country: 'Philippines', niche: 'Buy/Sell' },
    { name: 'laptop sales', url: 'https://www.facebook.com/groups/287101333022830/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'Laptop Market', url: 'https://www.facebook.com/groups/800666933317125/', country: 'Mixed', niche: 'Generic' },
    { name: 'SECOND HAND LAPTOPS FOR SALE PHILIPPINES', url: 'https://www.facebook.com/groups/377014119543562/', country: 'Philippines', niche: 'Buy/Sell' },
    { name: 'Laptops', url: 'https://www.facebook.com/groups/3401714916803226/', country: 'Mixed', niche: 'Generic' },
    { name: 'PPG PAKISTAN PC/LAPTOP GAMERS BUY & SELL', url: 'https://www.facebook.com/groups/pakpcgames/', country: 'Pakistan', niche: 'Gaming' },
    { name: 'PM Laptop Scheme 2025', url: 'https://www.facebook.com/groups/777144327402377/', country: 'Pakistan', niche: 'Education' },
    { name: 'Computer accessories buy and sale �', url: 'https://www.facebook.com/groups/1512262816124754/', country: 'Mixed', niche: 'Accessories' },
    { name: 'COMPUTER BUY AND SELL DESKTOP AND LAPTOP - WEFIX', url: 'https://www.facebook.com/groups/937271833049310/', country: 'Mixed', niche: 'Buy/Sell' },
    { name: 'Pakistan Pc Gaming Community (PPGC)', url: 'https://www.facebook.com/groups/363989313804879/', country: 'Pakistan', niche: 'Gaming' },
    { name: 'PC Gamers Of Pakistan (PGOP) 2.0', url: 'https://www.facebook.com/groups/479403642129889/', country: 'Pakistan', niche: 'Gaming' },
    { name: 'PC Gamers Of Pakistan☑️ (PGOP)', url: 'https://www.facebook.com/groups/pak.gamers2/', country: 'Pakistan', niche: 'Gaming' },
    { name: 'Laptop Sale House Karachi', url: 'https://www.facebook.com/groups/216672570118015/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Pakistan Laptop Market', url: 'https://www.facebook.com/groups/pakistanlaptopmarket/', country: 'Pakistan', niche: 'Buy/Sell' },
    { name: 'Gaming laptops in UAE', url: 'https://www.facebook.com/groups/1412662206198864/', country: 'UAE', niche: 'Gaming' },
    { name: 'SECOND HAND LAPTOP SHOWROOM', url: 'https://www.facebook.com/groups/1179395799242240/', country: 'Mixed', niche: 'Buy/Sell' },
  ],
  sourcing: [
    { name: 'Laptop Wholesale UAE JNP Market', url: 'https://www.facebook.com/groups/825786222286586/', country: 'UAE', niche: 'Wholesale' },
    { name: 'Sharjah Laptops Wholesale Market', url: 'https://www.facebook.com/groups/2884475155068867/', country: 'UAE', niche: 'Wholesale' },
    { name: 'Laptops Wholesalers Sharjah Market', url: 'https://www.facebook.com/groups/600632672583587/', country: 'UAE', niche: 'Wholesale' },
    { name: 'JNP Computer Market ( JNP Signal Sharjah )', url: 'https://www.facebook.com/groups/1478102003150105/', country: 'UAE', niche: 'Wholesale' },
    { name: 'laptops JNP sharjah UAE', url: 'https://www.facebook.com/groups/1883316978974512/', country: 'UAE', niche: 'Wholesale' },
    { name: 'Laptop and Accessories Wholesale UAE', url: 'https://www.facebook.com/groups/1280232569633019/', country: 'UAE', niche: 'Wholesale' },
    { name: 'Laptop Wholesale & Repair', url: 'https://www.facebook.com/groups/1648365779101841/', country: 'UAE', niche: 'Wholesale/Repair' },
    { name: 'FREIGHT & CARGO SHIPPING IN DUBAI UAE', url: 'https://www.facebook.com/groups/freightcargoshipping/', country: 'UAE', niche: 'Import/Export' },
    { name: 'Dubai Cargo & Freight Services - Import & Export UAE', url: 'https://www.facebook.com/groups/1145933026990965/', country: 'UAE', niche: 'Import/Export' },
    { name: 'Sharjah JNP Laptops Market', url: 'https://www.facebook.com/groups/720614693254715/', country: 'UAE', niche: 'Wholesale' },
    { name: 'Computer parts ram ssd cpu desktop Laptop server', url: 'https://www.facebook.com/groups/581368450568963/', country: 'Mixed', niche: 'Parts' },
    { name: 'Cavite computer parts buy and sell', url: 'https://www.facebook.com/groups/841260939388984/', country: 'Philippines', niche: 'Parts' },
    { name: 'HP Laptop Parts & Accessories (Zimbabwe)', url: 'https://www.facebook.com/groups/449428265500354/', country: 'Zimbabwe', niche: 'Parts' },
    { name: 'Direct Supplier Of Computer/Laptop Accessories Buy&Sell', url: 'https://www.facebook.com/groups/818328635248750/', country: 'Mixed', niche: 'Accessories' },
    { name: 'BUY SELL OLD & NEW COMPUTER PARTS IN INDIA', url: 'https://www.facebook.com/groups/885057798213897/', country: 'India', niche: 'Parts' },
    { name: 'Second Hand PC Parts By Magical Computer\'s', url: 'https://www.facebook.com/groups/465732824850167/', country: 'India', niche: 'Parts' },
    { name: 'Computer Parts අඩුවට', url: 'https://www.facebook.com/groups/1238712033412630/', country: 'Sri Lanka', niche: 'Parts' },
    { name: 'Laptop Parts - SriLanka', url: 'https://www.facebook.com/groups/2715053998708483/', country: 'Sri Lanka', niche: 'Parts' },
    { name: 'Jnp signal sharjah Laptops ( Wholesale & Retail)', url: 'https://www.facebook.com/groups/934845631342971/', country: 'UAE', niche: 'Wholesale' },
    { name: 'America original used laptops and iPhones wholesale in Dubai', url: 'https://www.facebook.com/groups/1255894315778390/', country: 'UAE', niche: 'Wholesale' },
    { name: 'USA | Canada Original Laptop in Singapore', url: 'https://www.facebook.com/groups/428528275569574/', country: 'Singapore', niche: 'Wholesale' },
    { name: 'Laptop RAM,HDD,Screen &keyboard Reseller.', url: 'https://www.facebook.com/groups/954445709861363/', country: 'Mixed', niche: 'Parts' },
    { name: 'Laptop Keyboards,Laptop Battery,Laptop Chargers Computer Laptop Accessories', url: 'https://www.facebook.com/groups/laptopkeyboardbattery/', country: 'Mixed', niche: 'Accessories' },
    { name: 'All laptop motherboard wholesale & retail', url: 'https://www.facebook.com/groups/335590945025757/', country: 'Mixed', niche: 'Parts' },
    { name: 'Sharjah JNP wholesale Laptop', url: 'https://www.facebook.com/groups/290838214864889/', country: 'UAE', niche: 'Wholesale' },
    { name: 'Laptop Parts Online in Pakistan', url: 'https://www.facebook.com/groups/laptoppartsonlineinpakistan/', country: 'Pakistan', niche: 'Parts' },
    { name: 'iPhone iPad Laptop Wholesale Group | Global B2B', url: 'https://www.facebook.com/groups/1234278492086949/', country: 'Global', niche: 'Wholesale B2B' },
    { name: 'LAPTOP WORLD - USED & REFURBISHED LAPTOPS - SHARJAH UAE', url: 'https://www.facebook.com/groups/laptops.wholesale/', country: 'UAE', niche: 'Wholesale' },
    { name: 'Laptops Dealers India', url: 'https://www.facebook.com/groups/579436678810030/', country: 'India', niche: 'Dealers' },
    { name: 'ALL LAPTOP PARTS', url: 'https://www.facebook.com/groups/1071806191221847/', country: 'Mixed', niche: 'Parts' },
    { name: 'Pc hardware buy/sell SA', url: 'https://www.facebook.com/groups/1149405289822267/', country: 'South Africa', niche: 'Parts' },
    { name: 'Laptop and Computer PH Supplier&Reseller', url: 'https://www.facebook.com/groups/2062124537449385/', country: 'Philippines', niche: 'Supplier' },
    { name: 'BUY SELL OLD & NEW COMPUTER PARTS IN pakistan', url: 'https://www.facebook.com/groups/2721275798037845/', country: 'Pakistan', niche: 'Parts' },
    { name: 'Laptops wholesale Dubai', url: 'https://www.facebook.com/groups/5107883435949077/', country: 'UAE', niche: 'Wholesale' },
    { name: 'Post mo Laptop/Desktop, Parts, Motherboards, Memory, Atbp.', url: 'https://www.facebook.com/groups/478535276508158/', country: 'Philippines', niche: 'Parts' },
  ],
  technical: [
    { name: 'Laptop Repair / Parts Defective Laptop', url: 'https://www.facebook.com/groups/240700502936080/', country: 'Mixed', niche: 'Repair/Parts' },
    { name: 'Laptop and computer repairs', url: 'https://www.facebook.com/groups/193091981052540/', country: 'Mixed', niche: 'Repair' },
    { name: 'Laptop Repair & BIOS', url: 'https://www.facebook.com/groups/146494622423037/', country: 'Mixed', niche: 'Repair' },
    { name: 'Laptop Repair Nairobi Kenya (0729496729)', url: 'https://www.facebook.com/groups/786506118877772/', country: 'Kenya', niche: 'Repair' },
    { name: 'Laptop repair kenya', url: 'https://www.facebook.com/groups/2840991392864811/', country: 'Kenya', niche: 'Repair' },
    { name: 'Laptop Repair & Spare Parts ☑️', url: 'https://www.facebook.com/groups/176142160831613/', country: 'Mixed', niche: 'Repair/Parts' },
    { name: 'Dead Laptops and spare parts', url: 'https://www.facebook.com/groups/107971584586589/', country: 'Mixed', niche: 'Parts/Spare' },
    { name: 'LAPTOP HARDWARE/SOFTWARE REPAIRS.', url: 'https://www.facebook.com/groups/787496323052527/', country: 'Mixed', niche: 'Repair' },
    { name: 'LAPTOP REPAIR', url: 'https://www.facebook.com/groups/391415187699794/', country: 'Mixed', niche: 'Repair' },
    { name: 'Laptop problems and solutions', url: 'https://www.facebook.com/groups/463158498736181/', country: 'Mixed', niche: 'Repair' },
  ],
};